listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip=<YOUR_PUBLIC_IP>
fingerprint
lt-cred-mech
realm=remoteview
user=username:password
min-port=49152
max-port=65535
no-multicast-peers
